[phases.setup]
nixPkgs = [
    'php82',
    'php82Extensions.pdo',
    'php82Extensions.pdo_mysql',
    'php82Extensions.sodium',
    'nodejs_20'
]
cmds = [
    "mkdir -p public/build/assets",
    "chmod -R 775 public/build",
    "ls -la public/build"
]

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx /var/cache/nginx",
    "export COMPOSER_ALLOW_SUPERUSER=1",  # Allow Composer plugins
    "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs",
    "npm install",
    "cp .env.example .env"
]

[phases.build]
cmds = [
    "echo 'Starting build process...'",
    "NODE_ENV=production npm run build",
    "ls -la public/build",
    "php artisan config:clear",
    "php artisan cache:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "echo 'Removing unnecessary files...'",
    "rm -rf node_modules",
    "echo 'Running migrations...'",
    "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"

[variables]
NODE_ENV = "production"
VITE_APP_URL = "https://vectoradminapp.vectorcr.com"
ASSET_URL = "/build"

[[ports]]
port = "8080"
