[phases.setup]
cmds = [
    "mkdir -p public/build/assets",
    "chmod -R 775 public/build",
    "ls -la public/build",
    # Asegura que la carpeta de destino exista
    "mkdir -p /app/storage/app/certs",

    # Verifica que la carpeta contenga el archivo después de copiarlo
    "ls -la /app/storage/app/certs",

    # Asegura que los permisos del archivo sean correctos
    "chmod -R 755 /app/storage/app/certs/azure_ad_public_cert.cer"
]

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx /var/cache/nginx",
    "export COMPOSER_ALLOW_SUPERUSER=1",  # Allow Composer plugins
    "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs",
    "npm install",
    "cp .env.example .env"
]

[phases.build]
cmds = [
    "echo 'Starting build process...'",
    "NODE_ENV=production npm run build",
    "ls -la public/build",
    "php artisan config:clear",
    "php artisan cache:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "echo 'Removing unnecessary files...'",
    "rm -rf node_modules",
    "echo 'Running migrations...'",
    "php artisan migrate --force"
]

[variables]
NODE_ENV = "production"
VITE_APP_URL = "https://vectoradminapp.vectorcr.com"
ASSET_URL = "/build"

