name: "🇺🇸 🐛 Bug Report"
description: "Report something that isn't working as expected"
title: "[Bug]: "
labels: ["🐛 bug", "📋 triage"]
assignees:
  - vectorcr
projects:
  - "Vector-Costa-Rica/9" # Vector Backlog Project

body:
  - type: markdown
    attributes:
      value: |
        # 🙏 Thank you for your bug report!
        We appreciate your help in improving our service. Please provide a brief description of the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: "❓ What happened?"
      description: "Please describe what went wrong"
      placeholder: "When I tried to... the website..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "📝 Steps to reproduce"
      description: "How can we see this issue ourselves?"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Priority Level"
      description: "Select the impact level of this issue"
      options:
        - "🔥 p0-critical - Immediate attention required"
        - "🚨 p1-urgent - Address as soon as possible"
        - "⚡ p2-high - Plan to address soon"
        - "📊 p3-medium - Address in current sprint"
        - "📫 p4-low - Address when possible"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🏷️ Issue Category"
      description: "Select the type of issue"
      options:
        - "🎯 core - Core functionality changes"
        - "🎨 ui-ux - User interface and experience changes"
        - "⚡ performance - Performance related changes"
        - "🔒 security - Security related changes"
        - "📱 mobile - Mobile specific changes"
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: "🌐 Affected Browsers"
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Other

  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots"
      description: "If possible, add screenshots to help explain your problem"
      placeholder: "Drag and drop images here"

  - type: input
    id: contact
    attributes:
      label: "📧 Contact Details"
      description: "How can we get in touch with you if we need more info?"
      placeholder: "ex. email@example.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        📋 Your report will be reviewed by our team and added to our backlog.
        We'll be in touch if we need any additional information.
