name: "🇨🇷 🐛 Reporte de Error"
description: "Reportar algo que no está funcionando como se espera"
title: "[Error]: "
labels: ["🐛 bug", "📋 triage"]
assignees:
  - vectorcr
projects:
  - "Vector-Costa-Rica/9" # Vector Backlog Project

body:
  - type: markdown
    attributes:
      value: |
        # 🙏 ¡Gracias por reportar este error!
        Agradecemos su ayuda para mejorar nuestro servicio. Por favor, bríndenos una descripción breve del problema.

  - type: textarea
    id: what-happened
    attributes:
      label: "❓ ¿Qué sucedió?"
      description: "Por favor, describa qué salió mal"
      placeholder: "Cuando intenté... el sitio web..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "📝 Pasos para reproducir"
      description: "¿Cómo podemos ver este error nosotros mismos?"
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '....'
        3. Desplazarse hasta '....'
        4. Ver el error
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Nivel de Prioridad"
      description: "Seleccione el nivel de impacto de este problema"
      options:
        - "🔥 p0-crítico - Requiere atención inmediata"
        - "🚨 p1-urgente - Atender lo antes posible"
        - "⚡ p2-alto - Planear atender pronto"
        - "📊 p3-medio - Atender en el sprint actual"
        - "📫 p4-bajo - Atender cuando sea posible"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🏷️ Categoría del Problema"
      description: "Seleccione el tipo de problema"
      options:
        - "🎯 core - Cambios en funcionalidad principal"
        - "🎨 ui-ux - Cambios en interfaz y experiencia de usuario"
        - "⚡ performance - Cambios relacionados con rendimiento"
        - "🔒 security - Cambios relacionados con seguridad"
        - "📱 mobile - Cambios específicos para móviles"
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: "🌐 Navegadores Afectados"
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Otro

  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Capturas de Pantalla"
      description: "Si es posible, agregue capturas de pantalla para explicar el problema"
      placeholder: "Arrastre y suelte las imágenes aquí"

  - type: input
    id: contact
    attributes:
      label: "📧 Información de Contacto"
      description: "¿Cómo podemos contactarle si necesitamos más información?"
      placeholder: "ej. correo@ejemplo.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        📋 Nuestro equipo revisará su reporte y lo agregará a nuestro backlog.
        Nos pondremos en contacto si necesitamos información adicional.
