name: "🇨🇷 🔄 Solicitud de Refactorización"
description: "Solicitud para refactorizar o mejorar una parte específica del proyecto"
title: "[Refactorizar]: "
labels:
  - "🔄 enhancement"
  - "⚡ performance"
  - "🎯 core"
  - "📋 triage"
  - "⚙️ in-development"
  - "🎨 design-needed"
  - "🐜 size-xs"
  - "🦗 size-s"
  - "🐇 size-m"
  - "🦊 size-l"
  - "🦌 size-xl"
  - "🆘 help-wanted"
  - "👍 good-first-issue"
assignees:
  - vectorcr
projects:
  - "Vector-Costa-Rica/9" # Vector Backlog Project

body:
  - type: markdown
    attributes:
      value: |
        # 🙏 ¡Gracias por sugerir una refactorización!
        Agradecemos su contribución para mejorar la estructura y el rendimiento de nuestro proyecto. Por favor, bríndenos una breve descripción de la parte que desea refactorizar.

  - type: textarea
    id: what-to-refactor
    attributes:
      label: "❓ ¿Qué parte necesita refactorización?"
      description: "Describa la parte del proyecto que requiere mejora"
      placeholder: "Creo que el código de... podría ser optimizado..."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "💡 Razón para la Refactorización"
      description: "¿Por qué cree que esta parte debe ser refactorizada?"
      placeholder: |
        Podría estar desactualizado...
        Causa problemas de rendimiento...
        Es difícil de mantener...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Nivel de Prioridad"
      description: "Seleccione la prioridad de esta solicitud de refactorización"
      options:
        - "🔥 p0-crítico - Requiere atención inmediata"
        - "🚨 p1-urgente - Atender lo antes posible"
        - "⚡ p2-alto - Planear atender pronto"
        - "📊 p3-medio - Atender en el sprint actual"
        - "📫 p4-bajo - Atender cuando sea posible"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🏷️ Categoría de Refactorización"
      description: "Seleccione el tipo de refactorización"
      options:
        - "🎯 core - Mejoras en funcionalidad principal"
        - "⚡ performance - Optimización relacionada con rendimiento"
        - "💻 code - Estructura y legibilidad del código"
        - "🔒 security - Mejoras de seguridad"
        - "📱 mobile - Refactorización específica para móviles"
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "📊 Impacto Potencial"
      description: "¿Cuál podría ser el impacto esperado de esta refactorización?"
      placeholder: "Mejora en rendimiento, mejor mantenimiento, etc."
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: "📧 Información de Contacto"
      description: "¿Cómo podemos contactarle si necesitamos más información?"
      placeholder: "ej. correo@ejemplo.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        📋 Nuestro equipo revisará su solicitud y la agregará a nuestro backlog.
        Nos pondremos en contacto si necesitamos más información.
