name: Create Branch for New Issues

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      process_existing:
        description: "Process existing issues"
        required: true
        default: "false"
        type: boolean

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Create branch for new issue
        if: github.event_name == 'issues'
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          # Echo debug information
          echo "Creating branch for issue #${ISSUE_NUMBER}"
          echo "Issue title: ${ISSUE_TITLE}"

          # Create branch name
          SANITIZED_TITLE=$(echo "${ISSUE_TITLE}" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-' | tr ' ' '-')
          BRANCH_NAME="issue-${ISSUE_NUMBER}-${SANITIZED_TITLE}"

          echo "Branch name will be: ${BRANCH_NAME}"

          # Check if branch exists
          if ! git ls-remote --exit-code --heads origin "${BRANCH_NAME}"; then
            echo "Creating new branch: ${BRANCH_NAME}"

            # Configure git
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'

            # Create and push branch
            git checkout -b "${BRANCH_NAME}"
            git push origin "${BRANCH_NAME}"

            # Comment on issue
            gh issue comment "${ISSUE_NUMBER}" --body "Branch \`${BRANCH_NAME}\` created!"

            echo "Branch created successfully"
          else
            echo "Branch ${BRANCH_NAME} already exists"
          fi
